// Code generated by go-swagger; DO NOT EDIT.

// This file is part of MinIO Console Server
// Copyright (c) 2022 MinIO, Inc.
//
// This program is free software: you can redistribute it and/or modify
// it under the terms of the GNU Affero General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU Affero General Public License for more details.
//
// You should have received a copy of the GNU Affero General Public License
// along with this program.  If not, see <http://www.gnu.org/licenses/>.
//

package bucket

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/minio/console/models"
)

// GetBucketACLOKCode is the HTTP code returned for type GetBucketACLOK
const GetBucketACLOKCode int = 200

/*
GetBucketACLOK A successful response.

swagger:response getBucketAclOK
*/
type GetBucketACLOK struct {

	/*
	  In: Body
	*/
	Payload string `json:"body,omitempty"`
}

// NewGetBucketACLOK creates GetBucketACLOK with default headers values
func NewGetBucketACLOK() *GetBucketACLOK {

	return &GetBucketACLOK{}
}

// WithPayload adds the payload to the get bucket Acl o k response
func (o *GetBucketACLOK) WithPayload(payload string) *GetBucketACLOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get bucket Acl o k response
func (o *GetBucketACLOK) SetPayload(payload string) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetBucketACLOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	payload := o.Payload
	if err := producer.Produce(rw, payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}
}

/*
GetBucketACLDefault Generic error response.

swagger:response getBucketAclDefault
*/
type GetBucketACLDefault struct {
	_statusCode int

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewGetBucketACLDefault creates GetBucketACLDefault with default headers values
func NewGetBucketACLDefault(code int) *GetBucketACLDefault {
	if code <= 0 {
		code = 500
	}

	return &GetBucketACLDefault{
		_statusCode: code,
	}
}

// WithStatusCode adds the status to the get bucket Acl default response
func (o *GetBucketACLDefault) WithStatusCode(code int) *GetBucketACLDefault {
	o._statusCode = code
	return o
}

// SetStatusCode sets the status to the get bucket Acl default response
func (o *GetBucketACLDefault) SetStatusCode(code int) {
	o._statusCode = code
}

// WithPayload adds the payload to the get bucket Acl default response
func (o *GetBucketACLDefault) WithPayload(payload *models.Error) *GetBucketACLDefault {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get bucket Acl default response
func (o *GetBucketACLDefault) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetBucketACLDefault) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(o._statusCode)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
