// Code generated by go-swagger; DO NOT EDIT.

// This file is part of MinIO Console Server
// Copyright (c) 2022 MinIO, Inc.
//
// This program is free software: you can redistribute it and/or modify
// it under the terms of the GNU Affero General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU Affero General Public License for more details.
//
// You should have received a copy of the GNU Affero General Public License
// along with this program.  If not, see <http://www.gnu.org/licenses/>.
//

package bucket

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/minio/console/models"
)

// SetACLWithBucketOKCode is the HTTP code returned for type SetACLWithBucketOK
const SetACLWithBucketOKCode int = 200

/*
SetACLWithBucketOK A successful response.

swagger:response setAclWithBucketOK
*/
type SetACLWithBucketOK struct {

	/*
	  In: Body
	*/
	Payload bool `json:"body,omitempty"`
}

// NewSetACLWithBucketOK creates SetACLWithBucketOK with default headers values
func NewSetACLWithBucketOK() *SetACLWithBucketOK {

	return &SetACLWithBucketOK{}
}

// WithPayload adds the payload to the set Acl with bucket o k response
func (o *SetACLWithBucketOK) WithPayload(payload bool) *SetACLWithBucketOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the set Acl with bucket o k response
func (o *SetACLWithBucketOK) SetPayload(payload bool) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *SetACLWithBucketOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	payload := o.Payload
	if err := producer.Produce(rw, payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}
}

/*
SetACLWithBucketDefault Generic error response.

swagger:response setAclWithBucketDefault
*/
type SetACLWithBucketDefault struct {
	_statusCode int

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewSetACLWithBucketDefault creates SetACLWithBucketDefault with default headers values
func NewSetACLWithBucketDefault(code int) *SetACLWithBucketDefault {
	if code <= 0 {
		code = 500
	}

	return &SetACLWithBucketDefault{
		_statusCode: code,
	}
}

// WithStatusCode adds the status to the set Acl with bucket default response
func (o *SetACLWithBucketDefault) WithStatusCode(code int) *SetACLWithBucketDefault {
	o._statusCode = code
	return o
}

// SetStatusCode sets the status to the set Acl with bucket default response
func (o *SetACLWithBucketDefault) SetStatusCode(code int) {
	o._statusCode = code
}

// WithPayload adds the payload to the set Acl with bucket default response
func (o *SetACLWithBucketDefault) WithPayload(payload *models.Error) *SetACLWithBucketDefault {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the set Acl with bucket default response
func (o *SetACLWithBucketDefault) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *SetACLWithBucketDefault) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(o._statusCode)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
