// Code generated by go-swagger; DO NOT EDIT.

// This file is part of MinIO Console Server
// Copyright (c) 2022 MinIO, Inc.
//
// This program is free software: you can redistribute it and/or modify
// it under the terms of the GNU Affero General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU Affero General Public License for more details.
//
// You should have received a copy of the GNU Affero General Public License
// along with this program.  If not, see <http://www.gnu.org/licenses/>.
//

package user

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/minio/console/models"
)

// GetUserDetailOKCode is the HTTP code returned for type GetUserDetailOK
const GetUserDetailOKCode int = 200

/*
GetUserDetailOK A successful response.

swagger:response getUserDetailOK
*/
type GetUserDetailOK struct {

	/*
	  In: Body
	*/
	Payload *models.UserDetail `json:"body,omitempty"`
}

// NewGetUserDetailOK creates GetUserDetailOK with default headers values
func NewGetUserDetailOK() *GetUserDetailOK {

	return &GetUserDetailOK{}
}

// WithPayload adds the payload to the get user detail o k response
func (o *GetUserDetailOK) WithPayload(payload *models.UserDetail) *GetUserDetailOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get user detail o k response
func (o *GetUserDetailOK) SetPayload(payload *models.UserDetail) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetUserDetailOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

/*
GetUserDetailDefault Generic error response.

swagger:response getUserDetailDefault
*/
type GetUserDetailDefault struct {
	_statusCode int

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewGetUserDetailDefault creates GetUserDetailDefault with default headers values
func NewGetUserDetailDefault(code int) *GetUserDetailDefault {
	if code <= 0 {
		code = 500
	}

	return &GetUserDetailDefault{
		_statusCode: code,
	}
}

// WithStatusCode adds the status to the get user detail default response
func (o *GetUserDetailDefault) WithStatusCode(code int) *GetUserDetailDefault {
	o._statusCode = code
	return o
}

// SetStatusCode sets the status to the get user detail default response
func (o *GetUserDetailDefault) SetStatusCode(code int) {
	o._statusCode = code
}

// WithPayload adds the payload to the get user detail default response
func (o *GetUserDetailDefault) WithPayload(payload *models.Error) *GetUserDetailDefault {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get user detail default response
func (o *GetUserDetailDefault) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetUserDetailDefault) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(o._statusCode)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
