// Code generated by go-swagger; DO NOT EDIT.

// This file is part of MinIO Console Server
// Copyright (c) 2022 MinIO, Inc.
//
// This program is free software: you can redistribute it and/or modify
// it under the terms of the GNU Affero General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU Affero General Public License for more details.
//
// You should have received a copy of the GNU Affero General Public License
// along with this program.  If not, see <http://www.gnu.org/licenses/>.
//

package object

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/minio/console/models"
)

// GetObjectACLOKCode is the HTTP code returned for type GetObjectACLOK
const GetObjectACLOKCode int = 200

/*
GetObjectACLOK A successful response.

swagger:response getObjectAclOK
*/
type GetObjectACLOK struct {

	/*
	  In: Body
	*/
	Payload string `json:"body,omitempty"`
}

// NewGetObjectACLOK creates GetObjectACLOK with default headers values
func NewGetObjectACLOK() *GetObjectACLOK {

	return &GetObjectACLOK{}
}

// WithPayload adds the payload to the get object Acl o k response
func (o *GetObjectACLOK) WithPayload(payload string) *GetObjectACLOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get object Acl o k response
func (o *GetObjectACLOK) SetPayload(payload string) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetObjectACLOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	payload := o.Payload
	if err := producer.Produce(rw, payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}
}

/*
GetObjectACLDefault Generic error response.

swagger:response getObjectAclDefault
*/
type GetObjectACLDefault struct {
	_statusCode int

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewGetObjectACLDefault creates GetObjectACLDefault with default headers values
func NewGetObjectACLDefault(code int) *GetObjectACLDefault {
	if code <= 0 {
		code = 500
	}

	return &GetObjectACLDefault{
		_statusCode: code,
	}
}

// WithStatusCode adds the status to the get object Acl default response
func (o *GetObjectACLDefault) WithStatusCode(code int) *GetObjectACLDefault {
	o._statusCode = code
	return o
}

// SetStatusCode sets the status to the get object Acl default response
func (o *GetObjectACLDefault) SetStatusCode(code int) {
	o._statusCode = code
}

// WithPayload adds the payload to the get object Acl default response
func (o *GetObjectACLDefault) WithPayload(payload *models.Error) *GetObjectACLDefault {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get object Acl default response
func (o *GetObjectACLDefault) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetObjectACLDefault) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(o._statusCode)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
